[2024-11-15T16:30:37.921+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-15T16:30:37.956+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FLOAT_DATA_TO_PG.ingest_to_postgres manual__2024-11-15T16:30:00.141431+00:00 [queued]>
[2024-11-15T16:30:37.967+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FLOAT_DATA_TO_PG.ingest_to_postgres manual__2024-11-15T16:30:00.141431+00:00 [queued]>
[2024-11-15T16:30:37.968+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-15T16:30:38.186+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ingest_to_postgres> on 2024-11-15 16:30:00.141431+00:00
[2024-11-15T16:30:38.197+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=147) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T16:30:38.199+0000] {standard_task_runner.py:63} INFO - Started process 156 to run task
[2024-11-15T16:30:38.199+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'FLOAT_DATA_TO_PG', 'ingest_to_postgres', 'manual__2024-11-15T16:30:00.141431+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/etl_process_float_data.py', '--cfg-path', '/tmp/tmpvkuopnqe']
[2024-11-15T16:30:38.202+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask ingest_to_postgres
[2024-11-15T16:30:38.267+0000] {task_command.py:426} INFO - Running <TaskInstance: FLOAT_DATA_TO_PG.ingest_to_postgres manual__2024-11-15T16:30:00.141431+00:00 [running]> on host 35eb7317174e
[2024-11-15T16:30:38.482+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='FLOAT_DATA_TO_PG' AIRFLOW_CTX_TASK_ID='ingest_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T16:30:00.141431+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T16:30:00.141431+00:00'
[2024-11-15T16:30:38.484+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-15T16:30:38.529+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-15T16:30:38.529+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_process_float_data.py", line 56, in ingest_to_postgres
    postgres_hook = PostgresHook(postgres_conn_id=postgres_conn_id)
                    ^^^^^^^^^^^^
NameError: name 'PostgresHook' is not defined
[2024-11-15T16:30:38.550+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=FLOAT_DATA_TO_PG, task_id=ingest_to_postgres, run_id=manual__2024-11-15T16:30:00.141431+00:00, execution_date=20241115T163000, start_date=20241115T163037, end_date=20241115T163038
[2024-11-15T16:30:38.581+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task ingest_to_postgres (name 'PostgresHook' is not defined; 156)
[2024-11-15T16:30:38.597+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-15T16:30:38.648+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T16:30:38.650+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
