[2024-11-15T20:39:21.202+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-15T20:39:21.588+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FLOAT_DATA_TO_PG.ingest_to_postgres manual__2024-11-15T20:14:17.345848+00:00 [queued]>
[2024-11-15T20:39:21.615+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FLOAT_DATA_TO_PG.ingest_to_postgres manual__2024-11-15T20:14:17.345848+00:00 [queued]>
[2024-11-15T20:39:21.617+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-11-15T20:39:21.674+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ingest_to_postgres> on 2024-11-15 20:14:17.345848+00:00
[2024-11-15T20:39:21.696+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=515) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T20:39:21.703+0000] {standard_task_runner.py:63} INFO - Started process 524 to run task
[2024-11-15T20:39:21.702+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'FLOAT_DATA_TO_PG', 'ingest_to_postgres', 'manual__2024-11-15T20:14:17.345848+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/etl_process_float_data.py', '--cfg-path', '/tmp/tmp59e5c789']
[2024-11-15T20:39:21.713+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask ingest_to_postgres
[2024-11-15T20:39:21.917+0000] {task_command.py:426} INFO - Running <TaskInstance: FLOAT_DATA_TO_PG.ingest_to_postgres manual__2024-11-15T20:14:17.345848+00:00 [running]> on host 35eb7317174e
[2024-11-15T20:39:22.325+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='FLOAT_DATA_TO_PG' AIRFLOW_CTX_TASK_ID='ingest_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T20:14:17.345848+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T20:14:17.345848+00:00'
[2024-11-15T20:39:22.351+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-15T20:39:23.430+0000] {logging_mixin.py:188} INFO - Connecting to PostgreSQL at host.docker.internal:5432 with user admin
[2024-11-15T20:39:23.715+0000] {logging_mixin.py:188} INFO - Transformed data successfully ingested into PostgreSQL using pandas
[2024-11-15T20:39:23.716+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-15T20:39:23.719+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-15T20:39:23.770+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=FLOAT_DATA_TO_PG, task_id=ingest_to_postgres, run_id=manual__2024-11-15T20:14:17.345848+00:00, execution_date=20241115T201417, start_date=20241115T203921, end_date=20241115T203923
[2024-11-15T20:39:23.839+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-15T20:39:23.912+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T20:39:23.916+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
