[2024-11-15T20:39:12.339+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-15T20:39:13.228+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FLOAT_DATA_TO_PG.ingest_to_postgres manual__2024-11-15T20:20:16.923650+00:00 [queued]>
[2024-11-15T20:39:13.254+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FLOAT_DATA_TO_PG.ingest_to_postgres manual__2024-11-15T20:20:16.923650+00:00 [queued]>
[2024-11-15T20:39:13.256+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-15T20:39:13.300+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ingest_to_postgres> on 2024-11-15 20:20:16.923650+00:00
[2024-11-15T20:39:13.322+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=508) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T20:39:13.328+0000] {standard_task_runner.py:63} INFO - Started process 511 to run task
[2024-11-15T20:39:13.332+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'FLOAT_DATA_TO_PG', 'ingest_to_postgres', 'manual__2024-11-15T20:20:16.923650+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/etl_process_float_data.py', '--cfg-path', '/tmp/tmpop410jxf']
[2024-11-15T20:39:13.342+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask ingest_to_postgres
[2024-11-15T20:39:13.652+0000] {task_command.py:426} INFO - Running <TaskInstance: FLOAT_DATA_TO_PG.ingest_to_postgres manual__2024-11-15T20:20:16.923650+00:00 [running]> on host 35eb7317174e
[2024-11-15T20:39:14.068+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='FLOAT_DATA_TO_PG' AIRFLOW_CTX_TASK_ID='ingest_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T20:20:16.923650+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T20:20:16.923650+00:00'
[2024-11-15T20:39:14.073+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-15T20:39:14.319+0000] {logging_mixin.py:188} INFO - Connecting to PostgreSQL at host.docker.internal:5432 with user admin
[2024-11-15T20:39:14.678+0000] {logging_mixin.py:188} INFO - Transformed data successfully ingested into PostgreSQL using pandas
[2024-11-15T20:39:14.679+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-15T20:39:14.682+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-15T20:39:14.721+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=FLOAT_DATA_TO_PG, task_id=ingest_to_postgres, run_id=manual__2024-11-15T20:20:16.923650+00:00, execution_date=20241115T202016, start_date=20241115T203913, end_date=20241115T203914
[2024-11-15T20:39:14.797+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-15T20:39:14.871+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T20:39:14.877+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
